apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-db-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-db-redis
  template:
    metadata:
      labels:
        app: kube-db-redis
    spec:
      containers:
        - name: kube-db-redis
          image: "redis:latest"
          ports:
            - containerPort: 6379
      volumes:
        - name: kube-redis-data
          hostPath:
            path: /Users/jason/work/go/gin-fanyi-project/redis_data
            type: Directory