apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-go
  template:
    metadata:
      labels:
        app: kube-go
    spec:
      containers:
        - name: kube-go
          image: "fanyi:v1"
          ports:
            - name: http
              containerPort: 8080